"""Evaluation primitives; no empirical performance is generated by this module."""
from __future__ import annotations
import numpy as np


def quantile_loss(y, predictions, quantiles, scale=None):
    """Per-observation mean pinball loss, optionally divided by TRAIN-fitted scale.

    y: (n,), predictions: (n,q), scale: (n,) or scalar positive. This finite
    quantile average is NOT advertised as an exact CRPS.
    """
    y = np.asarray(y, dtype=float)
    pred = np.asarray(predictions, dtype=float)
    qs = np.asarray(quantiles, dtype=float)
    if y.ndim != 1 or qs.ndim != 1 or pred.shape != (len(y), len(qs)):
        raise ValueError("Expected y[n], predictions[n,q], quantiles[q]")
    if len(qs) == 0 or not np.all((qs > 0) & (qs < 1)) or not np.all(np.diff(qs) > 0):
        raise ValueError("Quantiles must be strictly increasing and between zero and one")
    if not np.isfinite(y).all() or not np.isfinite(pred).all():
        raise ValueError("Scoring requires finite observations and predictions")
    residual = y[:, None] - pred
    loss = np.maximum(qs * residual, (qs - 1) * residual).mean(axis=1)
    if scale is not None:
        s = np.asarray(scale, dtype=float)
        if s.shape not in ((), y.shape) or not np.isfinite(s).all() or not np.all(s > 0):
            raise ValueError("scale must be a positive scalar or length-n array")
        loss = loss / s
    return loss


def paired_time_block_ci(date_level_improvement, block_length=8, n_boot=2000, seed=731):
    """Circular moving-block CI for baseline loss minus candidate loss.

    Input MUST already be aggregated across the matched asset panel per date.
    Market dates, not assets/training seeds, are the resampling units. Block
    stationarity is an approximation; regime sensitivity and short samples
    require additional interpretation.
    """
    x = np.asarray(date_level_improvement, dtype=float)
    if x.ndim != 1 or not np.isfinite(x).all():
        raise ValueError("Expected finite, date-ordered one-dimensional differences")
    if not isinstance(block_length, int) or not 1 <= block_length <= len(x):
        raise ValueError("Invalid block length")
    if not isinstance(n_boot, int) or n_boot < 100:
        raise ValueError("Use at least 100 bootstrap draws")
    rng = np.random.default_rng(seed)
    count = int(np.ceil(len(x)/block_length))
    results = np.empty(n_boot)
    offset = np.arange(block_length)
    for i in range(n_boot):
        starts = rng.integers(0, len(x), size=count)
        indices = ((starts[:, None] + offset) % len(x)).ravel()[:len(x)]
        results[i] = x[indices].mean()
    lo, hi = np.quantile(results, [0.025, 0.975])
    return {"mean_improvement": float(x.mean()), "lower_95": float(lo),
            "upper_95": float(hi), "n_dates": len(x), "block_length": block_length,
            "n_boot": n_boot, "seed": seed}
