"""Executed synthetic signed import acceptance and real-empty-registry rejection demo."""
import os,sys,json,base64,subprocess,csv
from pathlib import Path
from signalforge.runtime import now,file_hash
from qualification_v35.core import canonical,sha
from evidence_procurement_v37.core import accept,register_import
from evidence_procurement_v37.tiingo_beta_action_bridge import reconcile
R=Path('/mnt/c/Users/USERNAME/Downloads/SignalForge-QX-v33-dev');T=Path('/home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering');O=R/'reports/evidence_procurement_v37'
def demonstrate():
    d=T/'evidence_procurement_v37/TEST_ONLY_demo';inbox=d/'inbox';inbox.mkdir(parents=True,exist_ok=True);key=d/'TEST_ONLY_NOT_AUTHORITY.pem';assert not key.exists(),'Preserve prior demo; do not regenerate identity';subprocess.run(['openssl','genpkey','-algorithm','ED25519','-out',str(key)],check=True,capture_output=True);pub=subprocess.check_output(['openssl','pkey','-in',str(key),'-pubout','-outform','DER'])[-32:].hex()
    row={'event_id':'TEST_ONLY_ACTION','version_id':'TEST_ONLY_v1','provider':'TEST_ONLY_VENDOR','publisher':'fixture.invalid','kind':'dividend','entity':'IEF','field':'distribution','unit':'USD_per_share','valid_at':'2023-02-01T00:00:00Z','known_at':None,'first_public_at':None,'clock_basis':'unverified','correction_chain':[],'values':{'ticker':'IEF','permaTicker':'TEST_ONLY_NOT_ACTUAL_PERMATICKER','exDate':'2023-02-01','paymentDate':'2023-02-07','recordDate':'2023-02-02','declarationDate':'2023-01-20','distribution':.212178,'distributionFrequency':'m','currency':'USD'},'test_not_evidence':True};payload=canonical({'schema':'v37-authorized-events-1','records':[row]});p=inbox/'TEST_ONLY_payload.json';p.write_bytes(payload)
    body={'domain':'v37-authorized-pre2024-export-1','dataset_id':'TEST_ONLY_demo_v1','provider':'TEST_ONLY_VENDOR','publisher':'fixture.invalid','scope':'PRE_2024_ONLY','snapshot_asof':'2023-12-31T23:59:59Z','range_start':'2023-01-01','range_end':'2023-12-31','min_valid_at':'2023-01-01T00:00:00Z','max_valid_at':'2023-12-31T23:59:59Z','min_known_at':'2023-01-01T00:00:00Z','max_known_at':'2023-12-31T23:59:59Z','assets':['IEF'],'series':[],'row_count':1,'payload_bytes':len(payload),'payload_sha256':sha(payload),'version_ids':['TEST_ONLY_v1'],'excluded_rows_count':0,'independent_pre2024_export':True,'no_opaque_attachments':True,'license':{'research_use_permitted':True,'local_analysis_permitted':True,'entitlement_confirmed':True,'restrictions_resolved':True,'range_start':'2023-01-01','range_end':'2023-12-31','assets':['IEF'],'series':[],'license_record_id':'TEST_ONLY','public_redistribution_permitted':False},'test_not_evidence':True};b=d/'body.json';b.write_bytes(canonical(body));subprocess.run(['openssl','pkeyutl','-sign','-inkey',str(key),'-rawin','-in',str(b),'-out',str(d/'signature')],capture_output=True,check=True);m={'key_id':'TEST_ONLY_CUSTODIAN','body':body,'signature_b64':base64.b64encode((d/'signature').read_bytes()).decode()};manifest=d/'TEST_ONLY_manifest.json';manifest.write_text(json.dumps(m,indent=2));reg={'schema':'v37-trust-1','environment':'TEST_ONLY','independently_enrolled':True,'custodians':{'TEST_ONLY_CUSTODIAN':{'role':'authorized_export_custodian','public_key_hex':pub,'providers':['TEST_ONLY_VENDOR'],'publishers':['fixture.invalid'],'test_not_evidence':True,'enrollment_evidence_sha256':'a'*64}},'publishers':{},'reviewers':{}};registry=d/'TEST_ONLY_registry.json';registry.write_text(json.dumps(reg,indent=2))
    receipts=O/'import_receipts';db=T/'evidence_procurement_v37/TEST_ONLY_imports.sqlite';base=[sys.executable,'-m','evidence_procurement_v37.import_validation','--payload',str(p),'--manifest',str(manifest),'--registry',str(registry),'--inbox',str(inbox),'--receipt-dir',str(receipts),'--test-only','--record-db',str(db)];results=[]
    for i in [1,2]:
        result=subprocess.run(base,capture_output=True,text=True);print(result.stdout,flush=True);assert result.returncode==0;parsed=json.loads(result.stdout);results.append(parsed)
    assert results[1]['import_receipt']['state']=='IDEMPOTENT_REUSE'
    result=subprocess.run([sys.executable,'-m','evidence_procurement_v37.import_validation','--payload','/FORBIDDEN_UNREAD_PLACEHOLDER','--manifest',str(manifest),'--registry','evidence_procurement_v37/trust_registry.json','--inbox',str(T/'evidence_procurement_v37/inbox'),'--receipt-dir',str(receipts)],capture_output=True,text=True);print(result.stdout,flush=True);assert result.returncode==2;rejected=json.loads(result.stdout);assert rejected['reason']=='TRUST_NOT_INDEPENDENTLY_ENROLLED'
    legacy=list(csv.DictReader((R/'reports/p1_pit_v34/available_action_rows.csv').open()));assert len(legacy)==438 and all(x['ex_date']<'2024-01-01' for x in legacy) and all(not x['pay_date'] for x in legacy)
    issuer=list(csv.DictReader((R/'reports/data_recovery_v36/issuer_actions_delta.csv').open()));assert len(issuer)==24
    reconciliation=reconcile([row],legacy,issuer,body['snapshot_asof']);assert reconciliation['matched_legacy_rows']==1 and reconciliation['new_real_provider_matches']==0
    out={'observed_at':now(),'fixture_kind':'TEST_ONLY_NOT_SCIENTIFIC_EVIDENCE','fixture_payload_sha256':sha(payload),'manifest_path':str(manifest),'registry_path':str(registry),'payload_path':str(p),'inbox':str(inbox),'database':str(db),'accepted_cli':results,'real_rejection_cli':rejected,'safe_legacy_rows_read':438,'safe_issuer_partial_reference_rows':24,'legacy_action_file_sha256':file_hash(R/'reports/p1_pit_v34/available_action_rows.csv'),'reconciliation_fixture':reconciliation,'new_real_export_rows_received':0,'new_real_matches':0,'Tier_A':0,'P1':0,'no_original_rows_mutated':True}
    with (O/'executed_import_demo.json').open('x') as f:json.dump(out,f,indent=2)
    print('DEMO_PASS TEST_ONLY signed acceptance=1 immutable import; retry reused; REAL empty registry rejected BEFORE payload; actual received=0')
if __name__=='__main__':demonstrate()
