"""Outcome-blind procurement drafts and acceptance specifications. No messages sent."""
import json,csv
from pathlib import Path
from signalforge.runtime import now,file_hash,digest
from evidence_procurement_v37.core import BODY_FIELDS,ROW_FIELDS,LICENSE_FIELDS,KINDS
R=Path('/mnt/c/Users/USERNAME/Downloads/SignalForge-QX-v33-dev');Q=R/'evidence_procurement_v37';O=R/'reports/evidence_procurement_v37'
def write(name,x):
    with (O/name).open('x') as f:json.dump(x,f,indent=2,allow_nan=False)
def build():
    contacts=[
      {'provider':'Tiingo','route':'sales@tiingo.com','route_type':'official_sales_email','source':'https://app.tiingo.com/pricing/','verified_method':'official domain search-indexed pricing page; direct app rendering sparse','documentation':['https://www.tiingo.com/documentation/corporate-actions/dividends','https://www.tiingo.com/documentation/corporate-actions/splits','https://www.tiingo.com/documentation/end-of-day'],'entitlement':'UNVERIFIED; beta/enterprise versus EOD wording requires explicit confirmation'},
      {'provider':'EIA','route':'eiainfopetroleum@eia.gov','route_type':'official_team_email','source':'https://www.eia.gov/petroleum/supply/weekly/wpsr_ir-notice_06102026.php','verified_method':'official contact section only; linked2026 market sample not followed'},
      {'provider':'CFTC','route':'marketreports@cftc.gov','alternate':'publicreporting@cftc.gov','route_type':'official_report_and_portal_email','source':'https://publicreporting.cftc.gov/stories/s/r4w3-av2u','verified_method':'official domain indexed Contact Us; client-rendered direct page empty'},
      {'provider':'iShares/BlackRock','route':'https://www.ishares.com/us/about-us/contact-us','route_type':'official_contact_form_NOT_SUBMITTED','source':'https://www.ishares.com/us/about-us/contact-us','verified_method':'official contact form; no exact archival-team email verified'},
      {'provider':'St Louis Fed/FRED','route':'https://fred.stlouisfed.org/help/about/contact-us/contact-us','route_type':'official_contact_page_email_link','source':'https://fred.stlouisfed.org/help/about/contact-us/contact-us','documentation':['https://fred.stlouisfed.org/docs/api/fred/series_vintagedates.html','https://fred.stlouisfed.org/docs/api/fred/series_observations.html'],'verified_method':'official contact page; use its email link, no address guessed'},
      {'provider':'NYFed cash documentation','route':'https://www.newyorkfed.org/contacts','route_type':'official_directory_NOT_SUBMITTED','source':'https://www.newyorkfed.org/contacts','documentation':['https://markets.newyorkfed.org/static/docs/markets-api.html'],'verified_method':'official directory/API documentation; specific custodian email not invented'},
      {'provider':'External export custodian','route':None,'route_type':'ACTUAL_AUTHORIZED_CUSTODIAN_TO_BE_DESIGNATED','source':None,'verified_method':'no custodian designated'},
      {'provider':'Independent research reviewer','route':None,'route_type':'ACTUAL_INDEPENDENT_REVIEWER_TO_BE_DESIGNATED','source':None,'verified_method':'no independent reviewer designated'}]
    for x in contacts:x.update(status='DRAFT_NOT_SENT',observed_at=now(),first_public_evidence=False,account_or_provider_data_received=False)
    write('contact_registry.json',{'records':contacts,'external_messages_sent':0,'api_requests':0,'purchases':0,'verification_is_contact_documentation_not_data_certification':True})
    common='''Please supply only independently scoped historical records whose temporal fields and source-version snapshot are strictly before2024-01-01UTC. Withhold any2024+ data or mixed archives; provide attested excluded-row counts without disclosing their contents. We cannot inspect/filter a combined protected archive ourselves. Do not send credentials. Do not activate purchases, paid endpoints or additional charges. This inquiry requests a lawful delivery route, entitlement/license confirmation and evidence specification, not trading execution.\n\nPlease identify publisher/custodian, asset/share class or series, units, reference period, event/version IDs, exact byte SHA256, original/amended lineage and completeness. Distinguish declared/ex/record/payment CALENDAR dates from authenticated historical first dissemination aware UTC; retrieval time, schedules, database vintage and revised EOD data do not establish original availability. An independently enrolled custodian must sign the exact export manifest and license scope; first-public proof needs a publisher record linked to raw bytes and independent review. The supplied Ed25519 adapter is one precise profile; other authentic provider formats require a separately reviewed adapter, not an invented signature.\n'''
    letters=[
      ('Tiingo','sales@tiingo.com','Entitlement and historical corporate-action evidence: IEF/TLT2023 pilot;8-ETF2010–2023 scope', '''Hello Tiingo team,\n\nWe have438 legacy EOD action observations acrossSPY/QQQ/IEF/TLT/GLD/SLV/USO/UNG with no original pay_date fields; separate issuer documentation corroborates24IEF/TLT2023 ex/payment/amount tuples. A prior corporate-action API request was403, and will not be retried without verified lawful entitlement.\n\nPlease explicitly confirm the current account/product entitlement for beta distributions and splits, whether access is included for our EOD entitlement or requires enterprise/beta activation, and what missing/null date/history coverage means. Documentation contains both beta/enterprise and EOD inclusion text. Do not infer entitlement from this inquiry. Initial delivery request: IEF/TLT2023, then only after review all8assets2010-07-20 through2023-12-31.\n\nFor distributions deliver permaTicker,ticker,exDate,paymentDate,recordDate,declarationDate,distribution,distributionFrequency including cancellation c; currency and calendar/timezone semantics as supplemental export metadata. For splits deliver exDate,splitFrom,splitTo,splitFactor,splitStatus(a/c), IDs, original versions and cancellations. Confirm splitFactor=splitTo/splitFrom; cancelled events remain present but must not alter shares. Payment calendar dates do not attest an actual cash transfer. Null declaration/payment fields must remain null with a coverage explanation.\n\nProvide full-action and explicit no-action interval coverage, historical announcement/revision/distribution timestamps linked to original payloads, raw unadjusted EOD open versions and correction clocks, license/local-research rights and restrictions. We do not need adjusted-price substitution or distribution-yield/latest endpoints. The proposed specific-ticker historical routes are documented corporate-actions/<ticker>/distributions and /splits, but no API request is made here. Please validate exact bounded2023 query/export behavior, especially split end-date filtering, before authorized use. Do not return future dividends.\n\nReference comparison example—not a new provider response: IEF ex2023-02-01,payment2023-02-07,amountUSD0.212178. Can these fields and complete split/no-action coverage be delivered as an authorized pre2024-only export? What authentic original publication/correction proof is actually available?\n'''),
      ('EIA','eiainfopetroleum@eia.gov','Original Table4 versions and dissemination/correction records for four2023 releases', '''Hello EIA Petroleum Team,\n\nPlease provide original and amended Table4 editions for2023-08-16,08-23,12-20,12-28, linked reference weeks, US/PADD entity, million-barrel field units, version IDs and exact source hashes, plus complete correction/supersession history. Please identify the lawful archive path or custodian route for earlier2010-07-21/28 editions; the tested dated template returned404, not proof of absence.\n\nThe downloaded Dec28CSV has current−prior−reported-change residuals of−0.203(commercial crude),−0.094(gasoline),−0.092(distillate) million barrels; the rounded PDF crude residual is−0.2. The prior values agree with Dec20current values. Is there an actual amended edition or documented unrounded/basis/revision explanation? The propane/propylene appendix is not treated as a Table4 amendment.\n\nPlease supply per-version authenticated first-public UTC dissemination logs/receipts, source-channel and timezone semantics, not just the release schedule or present HTTP metadata. If such attestation is unavailable, please state that limitation and identify original-value/revision evidence you can actually provide.\n'''),
      ('CFTC','marketreports@cftc.gov; portal questions: publicreporting@cftc.gov','Original weekly2023 TFF/disaggregated editions and correction/dissemination lineage', '''Hello CFTC Market Reports team,\n\nWe verified current2023 annual history archives:2,809TFF futures rows and12,534disaggregated futures rows,52report dates each, Jan3–Dec26. These are positioning CONTRACTS, not flows, and an annual history download cannot authenticate original weekly availability.\n\nPlease provide individual original weekly2023 futures-only report payloads, exact contract codes/report-reference dates/units/version hashes, authenticated first dissemination UTC records and complete corrections/superseded editions. Clarify whether annual files are rewritten after corrections and how to identify original versus later versions. A subsequent full2010–2023 request depends on this outcome-blind2023 proof pilot.\n\nPlease identify any public publisher distribution log or authorized custodian delivery and permitted research usage. If only schedules/current-history files exist, please explicitly distinguish that from clock certification. Portal technical routing may be directed to publicreporting@cftc.gov.\n'''),
      ('iShares/BlackRock','Official contact form: https://www.ishares.com/us/about-us/contact-us','IEF/TLT2023 complete dividend/split/no-action and original-announcement custody', '''Hello iShares client service team,\n\nPlease route this request to the issuer distributions/corporate-actions records custodian. The official2023 tax distribution supplement corroborates24IEF/TLT ex/record/payment/amount tuples already in our partial audit; this retrospective content is not complete first-announcement evidence.\n\nPlease provide all2023 IEF/TLT dividends and splits/cancellations, exact share class/permanent identity, USD per-share amounts, declaration/record/ex/payment dates, original notices, revisions and authenticated original announcement distribution clocks. Please attest complete interval coverage including explicit no-action/split absence and identify coverage gaps. Any event with2024+ temporal fields must be withheld and counted, not silently called complete.\n\nExample: IEF ex2023-02-01,record2023-02-02,pay2023-02-07,amount0.212178. Explain legally permitted internal research use and reproducible source provenance. Initial scope2023 only;2010–2023/full8asset expansion is not inferred from this pilot. No exact archival-team email is presumed; this draft is prepared for the official form and has not been submitted.\n'''),
      ('St Louis Fed/FRED','Official email link: https://fred.stlouisfed.org/help/about/contact-us/contact-us','ALFRED original-value lineage versus authenticated original-release distribution clocks', '''Hello FRED/ALFRED support team,\n\nFor preregisteredCPIAUCSL,INDPRO,UNRATE,DGS2,DGS10 in2010–2023, please explain which value-vintage/original-release payload and correction evidence is available, and whether source-agency actual first-public dissemination clock attestation exists at per-version granularity. A database vintage date or series release date is not assumed to be an authenticated time of first publication.\n\nInitial documentary examples: G17Jan18/Dec15,2023 and original2023 source releases. Please identify the underlying source custodian/logs and lawful evidence delivery. INDPRO requires same-vintage12-month YoY derivation with preserved raw-base/unit metadata; historical indices must not be relabeled as a modern base. We are not asking to change series/date selection or disclose an API key. Please distinguish authenticated distribution-clock capability from the revision/new-release dates returned by the documented vintage-date endpoint.\n'''),
      ('Authorized external custodian','To be designated; no invented contact','Independently certified PRE2024 export, complete P1 field custody and as-of cash proof', '''Hello authorized data custodian,\n\nPlease deliver a separately audited pre2024-only export from lawful custody, not a combined archive for us to filter. Our mixed-clock canonical archive remains unread; its67,448aggregate versions have no new per-version re-audit. Required manifest: dataset/provider/publisher, exact payloadSHA256/bytes/row count/version IDs, asset/series roster, range, pre2024 min/max valid_at and known_at, snapshot_asof, independently scoped status, excluded counts only and permitted local-research license/entitlement. All temporal fields, original/revised payloads and attachments must fit scope; no sealed labels or opaque/unattested attachments.\n\nProvide authorized signer enrollment evidence via an independent verification route; we will not auto-enroll a key contained in a package. Sign domainv37-authorized-pre2024-export-1 and the exact canonical JSON. Original first-public and correction proofs need separate genuine publisher and independent-review records. If another legitimate authentication profile is used, supply semantics and verification material for a versioned adapter.\n\nP1 still has0/27,088qualified sessions: raw unadjusted execution opens and publication/permission proof;438legacy actions withoutpay fields;24partialIEF/TLT2023matches; full splits/dividends/no-action coverage; actual payment/known clocks; execution/cost conventions. NYFed4992023SOFR/EFFR quotes are effective-date rates, not as-of cash execution. Please coordinate an authenticated cash rate/version publication record, eligible actual cash instrument/holding, ACT360/compounding/calendar, account/accrual/fill conventions and legal permission. Official NYFed contact route: https://www.newyorkfed.org/contacts . No invented cash provider entitlement, payments or actual PnL.\n'''),
      ('Independent research reviewer','Genuine independent reviewer to be designated','Independent evidence and conditional future handoff review—no manufactured freeze', '''Hello independent research reviewer,\n\nPlease independently assess original source/version/correction/first-dissemination evidence, scoped export/usage permissions, P1 completeness and candidate/control/normalizer/target contracts. We need a genuine externally verified reviewer identity and role—not the developer, publisher/custodian or synthetic fixture key. No operational/scientific freeze currently exists, no candidate/control is selected for forward use, and there are0actual future observations/forecasts.\n\nP0 qualification is independent of P1 but still requires all-source TierA, reviewer, true scientific/operational freeze, explicit user candidate/control selection and exact benchmark binding. P1 requires every session-level joint proof before economic evaluation. Review the immutablev2/v34/v35/v36 evidence and preserved negative BAR/calibration results without retuning.\n\nProspective design remains two nonoverlap52mature distinct market-date cohorts per track×8assets×3seeds, fixed target/scoring scale and date-block bootstrap4/8/13; scheduleUNKNOWN. Actual access/issuance requires separate authorization after gates pass; do not backdate a freeze or treat TEST_ONLYshadow records as forecasts. Please identify missing evidence and attach domain-bound signed review only if genuinely earned. Reserved-final authorization and one-batch mechanisms remain sealed.\n''')]
    text='# V37 ready-to-review procurement drafts — DRAFT_NOT_SENT\n\nSeven requests below were prepared; no email/form/FOIA/purchase was sent. Contacts are routing evidence, not authenticated source data or account authorization. Subject/body are usable copy/paste drafts; no personal identifiers or credentials.\n'
    for provider,route,subject,body in letters:text+=f'\n## {provider}\n\nStatus: **DRAFT_NOT_SENT**\n\nTo/route: {route}\n\nSubject: {subject}\n\n{body}\n{common}\n'
    (O/'DRAFT_REQUEST_MESSAGES.md').write_text(text)
    schema={'$schema':'https://json-schema.org/draft/2020-12/schema','title':'V37 authorized pre2024 event export envelope','type':'object','required':['manifest','payload'],'additionalProperties':False,'properties':{'manifest':{'type':'object','required':['body','key_id','signature_b64'],'additionalProperties':False,'properties':{'key_id':{'type':'string'},'signature_b64':{'type':'string'},'body':{'type':'object','additionalProperties':False,'required':sorted(BODY_FIELDS),'properties':{k:{} for k in sorted(BODY_FIELDS)}}}},'payload':{'type':'object','required':['schema','records'],'additionalProperties':False,'properties':{'schema':{'const':'v37-authorized-events-1'},'records':{'type':'array','items':{'type':'object','additionalProperties':False,'required':sorted(ROW_FIELDS),'properties':{k:{} for k in sorted(ROW_FIELDS)}}}}}},'x_security_semantics':'Normative executable validator core.py enforces signatures, trust, times, bounded bytes, license and all kind-specific fields. JSON schema alone is not admission.'}
    mb=schema['properties']['manifest']['properties']['body']['properties'];mb['domain']={'const':'v37-authorized-pre2024-export-1'};mb['scope']={'const':'PRE_2024_ONLY'};mb['payload_sha256']={'type':'string','pattern':'^[0-9a-f]{64}$'};mb['license']={'type':'object','additionalProperties':False,'required':sorted(LICENSE_FIELDS),'properties':{k:{} for k in sorted(LICENSE_FIELDS)}};schema['properties']['payload']['properties']['records']['items']['properties']['kind']={'enum':sorted(KINDS)};write('approved_export_schema.json',schema)
    priorities=[{'rank':1,'owner':'Tiingo','scope':'IEF/TLT2023 then authorized8asset2010–2023','missing':'actual entitlement, dividendpayment/declaration, splits/cancellations, original versions and coverage','existing_evidence':'438legacy actions pay null;24issuerpartial matches','next_action':'Review/sendTiingo inquiry after explicit outbound approval; provider supplies scoped export','potential_scope_not_qualified':'438known action rows; no claimed sessions unlocked','new_qualified':0}, {'rank':2,'owner':'iShares','scope':'IEF/TLT2023','missing':'complete dividend/split/no-action interval and original announcement custody','existing_evidence':'24exact retrospective ex/pay tuples','next_action':'Approve official-form submission and request custodial delivery','potential_scope_not_qualified':'narrow issuer2023 scope, not all112assetyears','new_qualified':0}, {'rank':3,'owner':'External custodian','scope':'PRE2024 canonical/P1/cash export','missing':'independent signed scope, license, enrollment, asofcash/execution proofs','existing_evidence':'27088raw open bytes;499effective-date cash rates','next_action':'Designate genuine custodian; deliver manifest before payload','potential_scope_not_qualified':'67448aggregate versions and27088sessions with joint gates','new_qualified':0}, {'rank':4,'owner':'EIA','scope':'4releases2023 Table4','missing':'original/amended editions, arithmetic explanation and actual dissemination logs','existing_evidence':'CSV/PDF level consistency;4arithmetical failures','next_action':'Review/send EIA inquiry after approval','potential_scope_not_qualified':'20exact registered field/current values, not all EIA history','new_qualified':0}, {'rank':5,'owner':'CFTC','scope':'52weekly2023 futures reports','missing':'original individual editions, corrections, perversion dissemination','existing_evidence':'15343annual positioning rows','next_action':'Review/sendCFTC inquiry after approval','potential_scope_not_qualified':'annual rows are not qualified weekly originals','new_qualified':0}, {'rank':6,'owner':'FRED/source agencies','scope':'5registeredseries2010–2023','missing':'original clock evidence separate from vintage dates; exact source lineage','existing_evidence':'TierBmacro and2G17documents','next_action':'Use officialFRED contact to identify authentic custodian','potential_scope_not_qualified':'no clock-based qualification inferred','new_qualified':0}, {'rank':7,'owner':'Independent reviewer','scope':'P0/P1 scientific and future handoff','missing':'genuine reviewer, signed scope review, freezes and user/control selection','existing_evidence':'frozen historical studies andTEST_ONLYshadow48','next_action':'Designate actual independent reviewer; no fake signature','potential_scope_not_qualified':'overlapping joint gates, no quantitative benefit score','new_qualified':0}]
    with (O/'source_gap_priorities.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(priorities[0]));w.writeheader();w.writerows(priorities)
    write('hard_blocked_requirements.json',{'real_provider_exports_received':0,'trusted_custodians':0,'trusted_publishers':0,'independent_reviewers':0,'Tier_A':0,'P1_qualified_sessions':0,'P1_denominator':27088,'original_clock_certificates_received':0,'actual_forecasts':0,'future_dates':0,'freeze_created':False,'reserved_final':'SEALED','messages_sent':0,'purchases':0,'api_requests':0,'next_user_actions':['Review seven DRAFT_NOT_SENT messages and authorize outbound contacts if desired','Obtain explicitTiingo entitlement/history/license and pre2024-only export via provider; never pasteAPIkey','Designate genuine independent exportcustodian/reviewer and enroll verified public keys through independent evidence','Deliver signed manifest then authorized isolated-inbox payload; review gate-specific rejection receipts']})
    (O/'evidence_proof_submission_checklist.md').write_text('''# V37 evidence submission and trust checklist

DRAFT_NOT_SENT and importer readiness do not imply data obtained or science qualified.

1. Verify actual custodian identity/authority, licensed account/export rights and exact source; no token searching/retries. Independently enroll its public key with enrollment evidence SHA, provider/publisher scope and REAL role. Default registry is intentionally empty; never copy TEST_ONLY keys or self-declare trust from a manifest. Current importer will reject real submissions until enrollment is genuinely completed. Enrollment is a governance trust root, not something a payload can cryptographically establish itself.
2. Receive signed manifest BEFORE any dataset read. It must attest PRE_2024_ONLY and exact bytes, no opaque/mixed attachments, snapshot_asof and temporal extrema pre2024, excluded counts only and license scope. Do not open/filter original combined archive or files denied by gate. A signature attests custodian truthfulness; it cannot prove hidden content without reading it. The pre-read test rejects mixed/unsigned/unscoped manifests without reading; post-admission semantic validation detects inconsistent attested synthetic content. No actual mixed payload was inspected.
3. Stage ONLY authorized provider payload under isolated ext4 evidence_procurement_v37/inbox. Match rawSHA/bytes/rows/version roster and strict fields. All dates including payment/declaration/revisions must be pre2024; withholding cross-year events is a reported completeness gap, not no-action evidence.
4. Provide stable ticker/permaticker/share-class mapping, field/unit/basis, null metadata preserved, active/cancelled split ratio, no-action interval attestation and complete revisions. Supplementalcurrency must be supplied explicitly; it is not assumed a documentedTiingo field. Validate actual issuer tuples with unique asset/ex/amount matching. Do not patch legacy rows.
5. Original source evidence uses unchangedv35 strict qualifier and byte/clock/revision/reviewer linkage. Custodial export authorization is separate from publisher original availability. Different independent publisher/reviewer keys and authentic roles are required; calendardeclarationDate is not first dissemination time. RawEOD correction and retrieval clocks are not original opens. Effective-date cash quotes are not actual cash account returns/asof proof.
6. Inspect durable acceptance/rejection receipt with minimal missing proof list; do not edit controls to forcePASS. Imports have their own immutable idempotent registry, no old ledger access. P1 qualification stays0 unless every independent joint session proof is actually qualified through the existing scientific process.
7. No actual scientific/operational freeze or realforward API is implemented or run byv37. P0 needs its own TierA/reviewer/freezes/usercandidate/exactcontrol gates independent ofP1. Future2×52maturedate cohorts are still unavailable; reservedfinal remainssealed.

## Explicit invocation after authorized data arrives

Paths passed to the wrapper are WSL paths. Do not use original orchestration scripts or add global environment variables.

PowerShell7:
`pwsh -NoProfile -File C:\\Users\\USERNAME\\Downloads\\SignalForge-QX-v33-dev\\evidence_procurement_v37\\Validate-AuthorizedExport.ps1 -Payload /home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering/evidence_procurement_v37/inbox/provider.json -Manifest /home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering/evidence_procurement_v37/inbox/manifest.json`

WSL existing Python, cwd isolated root; PYTHONPATH=root:root/src, TMPDIR=isolatedext4/tmp, CUDA_VISIBLE_DEVICES empty, PYTHONDONTWRITEBYTECODE=1 and existingLD_LIBRARY_PATH set process-only:
`python -m evidence_procurement_v37.import_validation --payload <authorized-ext4-inbox/provider.json> --manifest <manifest.json> --registry evidence_procurement_v37/trust_registry.json --inbox /home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering/evidence_procurement_v37/inbox --receipt-dir reports/evidence_procurement_v37/import_receipts --record-db /home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering/evidence_procurement_v37/imports.sqlite`

Exit0 means authorized partial export/schema acceptance, never automaticP1/final/freeze. Exit2 means fail-closed rejection. No datafile is read before trust/scope/license gate. Unknown credentials/metadata must not be included in files. TEST_ONLY is solely for labeled software fixtures and is rejected by REALregistry; there is no genuineforecast command.
''')
    (Q/'EXECUTION_PLAN.md').write_text('# V37 executed scope\n\nPreflight protection, officialcontact/API documentation verification, sevenDRAFT_NOT_SENT requests, signed pre-readscope/license gate, action/issuer/clock reconciliation, scoped tests/independentverification and immutablehandoff. No email/APIdata/purchase/training/forwardfreeze. External data/identity/authority remain genuine blockers.\n')
if __name__=='__main__':build()
