"""Finished technical report from durable numerical CSVs; no speculative findings."""
from .source import *
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def md(df):
 cols=list(df.columns);lines=['| '+' | '.join(cols)+' |','| '+' | '.join(['---']*len(cols))+' |']
 for _,row in df.iterrows():
  vals=[]
  for v in row:
   if isinstance(v,(float,np.floating)):v='NA' if not np.isfinite(v) else f'{v:.6g}'
   vals.append(str(v).replace('|','/').replace('\n',' '))
  lines.append('| '+' | '.join(vals)+' |')
 return '\n'.join(lines)

def main():
 m=pd.read_csv(OUT/'overall_metrics.csv');a=pd.read_csv(OUT/'paired_loss_attribution.csv');gap=pd.read_csv(OUT/'OOF_outer_gap.csv');monitor=pd.read_csv(OUT/'monitor_summary.csv');inf=pd.read_csv(OUT/'stress_influence.csv');conc=pd.read_csv(OUT/'loss_concentration.csv');seed=pd.read_csv(OUT/'seed_functional_stability.csv');ranks=pd.read_csv(OUT/'seed_rank_stability.csv');p0=pd.read_csv(OUT/'P0_portfolio_materiality_proxy.csv');slices=pd.read_csv(OUT/'calibration_by_slice.csv');age=pd.read_csv(OUT/'outer_source_age_clock_audit.csv');bounds=pd.read_csv(OUT/'paired_date_block_bounds.csv');replay=pd.read_csv(OUT/'training_only_monitor_replay.csv');dis=pd.read_csv(OUT/'challenger_row_disagreement.csv')
 lines=['# SignalForge-QX v3.8 incremental model-risk and calibration audit','',f'Claim boundary: **{CLAIM}**. Developer self-audit, not external independent validation, regulatory approval, or a new holdout. All 2020/2022 development labels were already seen.','',
 '## Execution and preservation','CPU calculations only: five saved model families, two tracks, **12,480 outer rows**; each track/family has52 market dates ×8 assets ×3 seed repeats. Genuine SIA OOF has12,168 rows:441 Main-A and66 Nested-B dates. Existing120 actual CUDA fit/model/checkpoint bundles and48 v34 reports were verified; zero new fits, calibrator fits, GPU computations or downloads. Twelve prior SIA/BAR candidate bundles also revalidated without inference.','',
 'Original357 files and protected dev577 files matched their prior hashes at start and independent check; v2 code hash remains `'+FROZEN+'`. Original compute ledgers were **not reopened**, explicitly prohibited by this task. Ledger preservation references the existing v37 proof; this audit does not claim a fresh ledger-content read. Historical105 pass/1 fail source-hash incident and all previous receipts remain untouched. New v38 orchestration failures (Windows relative separators and hardware-name/device-alias assumption) are retained in failure receipts and attempted code; no scientific data repairs or exclusions.','',
 'Definitions were saved to frozen_plan.json before new panels were loaded; plan hash `'+readj(OUT/'source_index.json')['plan_sha256']+'`. Method/coverage matrix separates old completed21 CPU perturbations and99 tables from the new five-family/replay work. ABC is synthetic-only; full HPO/SSL/36/2392-fit programmes are not executed. No old model or outcome is overwritten.','',
 '## Scoring and interpretation','Pinball uses max(tau*(target-prediction),(tau-1)*(target-prediction)) in native units, divided by the exact train-only shared scale. Five quantiles averaged; seeds averaged within date/asset, assets equally within date, dates equally. Conditional slices use this same nested aggregation and at least13 distinct dates; smaller slices are UNDERPOWERED. Overall primary rows never filtered. Absolute/raw loss and all per-quantile errors are retained. Quantile reliability deviation is descriptive mean absolute coverage deviation, **not** classification ECE or a full CDF/PIT statistic. Five quantiles cannot identify PIT uniformity. At52 independent dates, expected5% tail support is2.6dates, not62.4independent asset/seed outcomes.','',
 md(m[['track','model','loss','raw_loss','coverage80','coverage90','normalized_bias','max_abs_forecast','p99_abs_forecast','catastrophic_rows']]),'',
 'SIA minus strong baseline: Main-A -0.005658702 (-1.1342%); Nested-B +0.001344311 (+0.4929%). BAR is worse by0.3801% /0.8046%. Calibrated SIA is worse than frozen SIA by0.2694% /0.3721%. These are matched-fold descriptive results, not final claims. Neither lower training loss nor more complex architecture warrants promotion.','',
 '## Calibration transport and damage','The genuine v34 SIA OOF supersedes the older report’s missing-SIA-OOF statement. BAR-specific OOF remains unavailable. The existing calibrator was train-only; this audit does not refit it. Independent scalar replay of frozen offsets and supported-segment projection matches all saved calibrated predictions exactly. Nested unsupported tails remain4992exact unchanged elements.','',
 md(m[['track','model','coverage_q05','coverage_q10','coverage_q50','coverage_q90','coverage_q95','width90','descriptive_mean_abs_quantile_coverage_deviation']]),'',
 md(gap[['track','metric','OOF','outer','outer_minus_OOF','OOF_dates']]),'',
 'Main-A OOF q95 coverage95.2948% becomes88.0609% outer;90% interval coverage91.4305% becomes79.9679%. Nested q10 moves9.5960%→26.4423%; q50 moves42.2980%→56.5705%. Different cohorts and changing train-only normalizers limit causal comparison. These transport gaps are consistent with distribution/regime shift; they do not prove a coding defect.','',
 'Nested’s positive median offsets correct an under-covered OOF median, but outer median is already over-covered: calibrated coverage becomes60.9776%. All Nested calibration loss damage comes from q50; unsupported tail quantiles stay identity. Main q05/q95 loss increases dominate, while q90 improves. Narrower intervals are not automatically better: Main90% coverage drops79.9679%→78.8462%.','',
 md(a[(a.dimension=='quantile')&(a.candidate=='SIA_calibrated_v34')][['track','value','within_slice_date_equal_delta','signed_loss_budget_contribution']]),'',
 '## Signed loss budgets, concentration and stress','Loss-budget contributions are signed shares of the untouched total loss difference. Asset/date/seed/quantile/regime partitions each sum to the overall delta; **do not add different partition dimensions together**. Overall loss concentration is different from incremental model-effect attribution.','',
 md(conc), '',
 md(a[(a.dimension=='asset')&(a.candidate=='SIA_v2')][['track','value','signed_loss_budget_contribution','within_slice_date_equal_delta']]),'',
 md(inf[(inf.candidate=='SIA_v2')&(((inf.operation=='LEAVE_ONE_ASSET_OUT')&(inf.excluded=='USO'))|((inf.operation=='LEAVE_ONE_STRONG_BASELINE_STRESS_WEEK_OUT')&inf.excluded.str.startswith('2020-04-24'))|inf.operation.str.startswith('REMOVE_TOP_K'))][['track','operation','excluded','original_delta','counterfactual_delta']]),'',
 'Main USO accounts for about48% of total loss, but removing it only for influence leaves SIA-minus-baseline -0.005055972; this is not evidence to delete USO. Removing2020-04-24 leaves -0.004518505. Signed primary improvement is therefore not entirely driven by that asset or week. All original stress rows remain in every primary metric. Residual signed bias, lag1–4/8 autocorrelation,13/26-date full-support rolling errors/coverage and ex-ante heteroscedasticity associations are in residual files. Correlation is descriptive, not proof of serial independence or source causality.','',
 '## Fixed regime and challenger diagnostics','Frozen pre-outer volatility,1w/4w-return, source availability/OOD and source-age thresholds are reused. Outcome-magnitude slices are explicitly OUTCOME_CONDITIONAL and cannot be prospective triggers. Source-mask perturbations are copied from existing21CPU runs: not causal, not exact CUDA ablation; historic maximum discrepancy4.3479e-6is preserved. log_volume is absent from saved ex-ante panel and marked BLOCKED_SAVED_FEATURE_ABSENT. No mixed canonical data was read.','',
 md(slices[(slices.slice=='realized_vol_20_regime')&slices.model.isin(['strong_I0','SIA_v2','SIA_calibrated_v34','BAR'])][['track','model','value','distinct_dates','loss','coverage90','status']]),'',
 md(dis.groupby(['track','candidate','control'])[['corrects_loss','hurts_loss','control_wrong_candidate_right','control_right_candidate_wrong','sign_disagreement','near_zero_control']].mean().reset_index()),'',
 'Challenger corrections/hurts are paired asset-date-seed descriptive fractions. Sign agreement is not profit; near-zero control is fixed |q50/scale|<0.001, not tuned from outcomes. Rank ties resolve descending q50 then lexical asset. All date/asset corrections and stress/regime links are retained, not selected for favorable findings.','',
 '## Functional seed stability','Checkpoint parameter cosine/norms from previous audit are reused as limited evidence; latent permutation makes naive tensor cosine unsuitable. New stability uses forecast span, q50 sign flips, interval-width dispersion and rank changes. Deterministic strong-baseline copies are duplicates, never additional independent samples.','',
 md(seed.groupby(['track','model'])[['median_span_normalized','median_sign_flip','width90_seed_std_normalized','max_quantile_span_normalized']].mean().reset_index()),'',
 md(ranks.groupby(['track','model'])[['top1_switch','top2_jaccard','spearman']].mean().reset_index()),'',
 '## New causal mature-OOF monitor replay','**4,737 chronological statistic/window/date records** were independently recomputed. A lagging value is available only at that date’s maximum label_available_at; prior dates must be strictly earlier decisions and fully mature by that computation time. Error is absolute q50 forecast error normalized by each existing train-only scale; asset/seed repetitions are averaged into one market-date statistic.90%miss fraction is1-interval coverage. Leading width uses earlier saved predictions and no labels; prediction lineage is retrospective prequential, not authenticated historic live issuance.','',
 'For window W=13/26 and lookback L=26/52, threshold=q95 of the latest L **past rolling-W statistics**, requiring L+W-1prior eligible dates. Current statistic uses latest W mature dates including current date. No outer data, new calibration or outcome-driven threshold selection is used. Latest data can trigger overlapping runs, so q95 does NOT imply5% false positives. Label maturity lag median is6.10417calendar days; no error warning is asserted at forecast time.','',
 md(monitor[['track','statistic','lookback','window','eligible_dates','exceedance_dates','exceedance_fraction','maximum_run','first_feasible_decision','state']]),'',
 'Main median-error L26/W13:72/403dates exceeded (17.866%); interval-miss77/403 (19.107%). Nested corresponding error3/28 (10.714%) and interval-miss5/28 (17.857%). This is historical diagnostic incidence, not verified false-positive rate. Nested L52/W13 has only2eligible dates; L52/W26 has0 and is UNDERPOWERED. q99 expected extreme-tail support is0.66dates for Nested: UNRELIABLE_TAIL; Main4.41dates also insufficient for calibrated tail-risk claims.','',
 'Predeclared circular date-block4/8/13 bootstrap,2000draws, fixed randomness produces **descriptive** bounds (paired_date_block_bounds.csv, monitor_date_block_bounds.csv). Market dates—not repeated rows—are resampled. Overlapping rolling windows, regime dependence, short cohorts, known outcomes and many comparisons prevent confirmatory confidence or model promotion. Main paired bounds change with block choice; do not choose the favorable block.','',
 md(bounds[['track','candidate','control','block','delta','lower_descriptive','upper_descriptive']]),'',
 'OOF source age/availability dependency clocks are absent: BLOCKED_UNVERIFIED_CLOCK, so these leading monitors were not fabricated. Outer-only1976registered source/asset/date age checks use prior train-only thresholds and existing v34 maximum-feature-dependency checks; they remain Tier B reconstructed dry runs. Baseline OOF warning references remain baseline-specific; they were not reused as BAR thresholds. BAR and original-RGMF model-specific OOF warning replay remains blocked. No alert notification or monitoring service was deployed.','',
 '## P0 materiality and controls','Fixed top1/top2/linear_rank signal mappings, asset cap0.25, commodity cap0.35, gross<=1 and cash remainder were reused. All29,952saved four-family weights match the new arithmetic. The same fixed rule extends to calibrated SIA;4,680group observations cover five families. HHI/effective holdings, seed/date stress exposure, L1changes vs strongest and turnover proxy are hypothetical P0 quantities—not economic returns or implementable fills.','',
 md(p0.groupby(['track','model','mapping'])[['gross_signal_weight','HHI_gross_normalized','effective_holdings','commodity_weight','L1_vs_strong','L1_turnover_proxy']].mean().reset_index()),'',
 'All21monitor definitions and11risk-register rows mapped to evidence, observed breach/support, source clocks, proposed UNAPPOINTED owner/cadence/escalation and hard-stop vs advisory controls. Current version is model_risk_control_map_current.csv; initial v38 map is retained. PSI/KS drift remains NOT_IMPLEMENTED_FORMAL_DISTRIBUTION_DRIFT, no after-the-fact threshold invented. Integrity guards are normative; statistical controls are unfrozen candidates. Synthetic injections test crossing, future feature, immature label, invalid/stale age, hash/checkpoint corruption, nonfinite values, duplicate key and absent signer. TEST_ONLY is not operational certification.','',
 '## Verification and limitations','Independent scalar branch and Decimal arithmetic reproduce all ten model/track scores and five quantile coverages. Maximum scalar-vs-Decimal row difference1.4211e-14. Separate scalar monitor reconstruction matches all4,737threshold/current values within2.7756e-15; exact frozen calibrator replay difference0. Current final scoped test receipt and additional independent verification are linked in final_completion.json. This is a developer two-implementation check, not external independent model validation.','',
 'BAR and calibrated SIA remain quarantined; frozen strongest I0 is retained as reference, SIA research-only. No architecture/seed/quantile/threshold/candidate was selected or promoted using these diagnostics. Genuine SIA OOF resolves one historic missing-data statement, but does not supply original publication evidence or a fresh market cohort.','',
 'Still blocked: authentic TierA clocks0; P1qualified0/27088; BAR-specific OOF; OOF source age clock lineage; appointed independent governance; valid operational/scientific freeze and independent future cohort (0dates). Reserved final stays sealed. No PnL/Sharpe/alpha/final/prospective claims permitted. Completion means this scoped CPU diagnostic audit, never whole-project scientific completion.','',
 '## Reproducible evidence','Code: model_risk_v38/source.py, diagnostics.py, monitor_replay.py, portfolio_proxy.py, supplement.py, controls_current.py, independent.py and scoped tests. Inputs: frozen source_index.json plus ext4 bundle hashes. Report/CSV/code output hashes and dedicated immutable ext4 archive are in final_completion.json. Run commands and failure traces are visible in the native Codex CLI; no unseen background delivery is promised.']
 (OUT/'V38_INCREMENTAL_MODEL_RISK_AND_CALIBRATION_REPORT.md').write_text('\n\n'.join(lines))
 fig,axes=plt.subplots(1,2,figsize=(12,4),constrained_layout=True)
 for ax,t in zip(axes,['Main-A','Nested-B']):
  ax.plot(Q,Q,'k--',label='Nominal')
  for model in ['strong_I0','SIA_v2','SIA_calibrated_v34']:
   row=m[(m.track==t)&(m.model==model)].iloc[0];ax.plot(Q,[row['coverage_'+c] for c in QC],marker='o',label=model)
  oo=gap[(gap.track==t)&gap.metric.str.startswith('coverage_q')];lookup=dict(zip(oo.metric,oo.OOF));ax.plot(Q,[lookup['coverage_'+c] for c in QC],marker='x',label='SIA mature OOF');ax.set(title=t+' descriptive quantile reliability',xlabel='Nominal quantile',ylabel='Observed coverage',xlim=(0,1),ylim=(0,1));ax.legend(fontsize=8);ax.grid(alpha=.2)
 fig.savefig(OUT/'quantile_reliability.png',dpi=160);plt.close(fig)
 fig,axes=plt.subplots(1,2,figsize=(12,4),constrained_layout=True)
 for ax,t in zip(axes,['Main-A','Nested-B']):
  g=a[(a.track==t)&(a.dimension=='quantile')&(a.candidate=='SIA_calibrated_v34')];ax.bar(g.value,g.signed_loss_budget_contribution,color=['#c84b40' if x>0 else '#3278a0' for x in g.signed_loss_budget_contribution]);ax.axhline(0,color='black',linewidth=.7);ax.set(title=t+' calibration loss budget',ylabel='Signed contribution to total normalized loss delta',xlabel='Quantile');ax.grid(axis='y',alpha=.2)
 fig.savefig(OUT/'calibration_loss_budget.png',dpi=160);plt.close(fig)
 fig,axes=plt.subplots(2,1,figsize=(12,7),constrained_layout=True)
 for ax,t in zip(axes,['Main-A','Nested-B']):
  g=replay[(replay.track==t)&(replay.statistic=='normalized_median_absolute_error')&(replay.lookback==26)&(replay.window==13)];date=pd.to_datetime(g.threshold_computation_time,utc=True);ax.plot(date,g.current_value,label='Mature trailing13-date q50 absolute error');ax.plot(date,g.threshold,label='q95 of prior26 rolling13-date values');ax.scatter(date[g.exceeded],g.current_value[g.exceeded],s=9,color='red',label='Descriptive exceedance');ax.set(title=t+' causal dry-run (not live alerts)',ylabel='Normalized mean absolute error');ax.legend(fontsize=8);ax.grid(alpha=.2)
 fig.savefig(OUT/'mature_threshold_replay.png',dpi=160);plt.close(fig)
 writej('report_metadata.json',{'report': 'V38_INCREMENTAL_MODEL_RISK_AND_CALIBRATION_REPORT.md','claim':CLAIM,'primary_rows':12480,'OOF_rows':12168,'monitor_replay_rows':4737,'new_training':0,'new_calibrators':0,'charts':['quantile_reliability.png','calibration_loss_budget.png','mature_threshold_replay.png'],'excluded_primary_rows':0})
 progress('TECHNICAL_REPORT_CREATED',{'report_lines':len(lines),'figures':3,'new_training':0})
if __name__=='__main__':main()
