"""Independent canonical version/payload hash and P1 action-clock readiness."""
import sys,json,csv,io,urllib.request,hashlib
from pathlib import Path
import numpy as np,pandas as pd
from signalforge.runtime import digest,file_hash,code_hash,atomic_json,validate_bundle,commit_bundle,now
from p1_pit_readiness_v34.gates import *
R=Path('/mnt/c/Users/USERNAME/Downloads/SignalForge-QX-v33-dev');ORIGINAL=Path('/mnt/c/Users/USERNAME/Downloads/SignalForge-QX');T=Path('/home/USERNAME/.local/share/signalforge-qx-v3/da768f7446b1');N=Path('/home/USERNAME/.local/share/signalforge-qx-v33-dev/isolated-engineering');O=R/'reports/p1_pit_v34'
def load(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def save(n,v):atomic_json(O/(n+'.json'),v)
def audit():
    historical=load(ORIGINAL/'reports/strict_pit_final_gate_audit.json');sources=[];versions=[]
    for card in historical['sources']:
        path=T/card['relative_path'];assert file_hash(path)==card['sha256'];validate_bundle(path.parent);events=load(path);assert len(events)==card['event_rows'];tiers={};clocks={};certified=0
        for i,row in enumerate(events):
            tier=row.get('pit_tier','UNKNOWN');tiers[tier]=tiers.get(tier,0)+1;clock=row.get('clock_evidence','NO_AUTHENTICATED_PUBLICATION_PROOF');clocks[clock]=clocks.get(clock,0)+1
            proof=row.get('original_publication_evidence',{});payload=row.get('raw_hash');ok=certify({'payload_sha256':payload},proof);certified+=int(ok)
            versions.append({'source':card['source'],'version_row':i,'entity':row.get('entity',row.get('asset')),'field':row.get('field'),'reference_time':row.get('reference_time'),'reconstructed_available_at':row.get('available_at'),'payload_sha256':payload,'tier':tier,'clock_evidence':clock,'original_flag':row.get('original_publication_qualified',False),'certified_first_public':ok,'missing':'authenticated per-version disseminated first clock, version link and complete correction history' if not ok else ''})
        sources.append({'source':card['source'],'rows':len(events),'sha256':file_hash(path),'tiers':tiers,'clock_evidence_counts':clocks,'certified_first_public_rows':certified,'state':'BLOCKED_TIER_A' if certified!=len(events) else 'QUALIFIED','missing_evidence':card['missing_evidence']})
    pd.DataFrame(versions).to_csv(O/'per_version_clock_audit.csv',index=False)
    market=T/'artifacts/tiingo_inputs/ba9be84158dedc267ba5191b298084ffa5cdc4e7dbe92bb105e828f7dd4062f0';validate_bundle(market);p=load(market/'p1_preparation.json');daily=pd.DataFrame(p['daily']);assert (pd.to_datetime(daily.session_date)<pd.Timestamp('2024-01-01')).all();assert len(daily)==27088;assert not daily.duplicated(['asset','session_date']).any();assert np.isfinite(daily.raw_open).all() and (daily.raw_open>0).all()
    actions=pd.DataFrame(p['actions']);actions.to_csv(O/'available_action_rows.csv',index=False);issuer=load(ORIGINAL/'reports/issuer_action_evidence_2023.json');validate_bundle(T/issuer['relative_bundle']);assert len(issuer['rows'])==24
    gaps=[];coverage=[];price_hash=file_hash(market/'p1_preparation.json')
    for asset,g in daily.groupby('asset'):
        a=actions[actions.asset==asset];coverage.append({'asset':asset,'sessions':len(g),'raw_open_present':True,'action_rows':len(a),'pay_date_missing':int(a.pay_date.isna().sum()) if len(a) else 0,'audited_actions':int(a.audited.sum()) if len(a) else 0})
        for date in g.session_date:
            for req in ['original_open_publication_clock','complete_action_no_action_attestation','asof_cash_benchmark']:
                gaps.append({'asset':asset,'date':date,'requirement':req,'state':'BLOCKED','raw_open_available':True,'evidence_sha256':price_hash})
    # Explicit every action event missing pay/announcement/split completeness.
    for row in p['actions']:
        gaps.append({'asset':row['asset'],'date':row['ex_date'],'requirement':'original_action_clock_and_actual_pay_date','state':'BLOCKED','raw_open_available':True,'evidence_sha256':price_hash})
    pd.DataFrame(gaps).to_csv(O/'p1_per_session_gaps.csv',index=False)
    yeargaps=[{'asset':asset,'year':year,'issuer_distribution_rows':sum(row['asset']==asset and row['pay_date'].endswith(str(year)) for row in issuer['rows']),'complete_actions_qualified':False,'first_announcement_clock_qualified':False,'allowed_next_evidence':'authentic issuer announcements/ex-payment/splits and no-action completeness attestation; cash provider as-of record'} for asset in sorted(daily.asset.unique()) for year in range(2010,2024)];pd.DataFrame(yeargaps).to_csv(O/'p1_asset_year_gaps.csv',index=False)
    # Verify documentary evidence only; do not retry private/403 endpoints.
    docs=[]
    for card in load(ORIGINAL/'reports/source_document_verification.json')['sources']:
        if 'raw' in card:
            raw=card['raw'];assert file_hash(raw['path'])==raw['sha256'];docs.append({'source':card['source'],'sha256':raw['sha256'],'url':raw['source_url'],'retrieved_at':raw['retrieved_at'],'schema_qualified':False,'first_public_certified':False})
    downloads=[]
    urls=['https://www.eia.gov/petroleum/supply/weekly/archive/2023/2023_12_28/pdf/appendix_e.pdf','https://www.ishares.com/us/literature/tax-information/2023-ishares-distribution-summary-stamped.pdf']
    for url in urls:
        try:
            with urllib.request.urlopen(url,timeout=30) as response:payload=response.read(8*1024*1024);headers={k:response.headers.get(k) for k in ['Content-Type','Last-Modified','ETag']}
            assert payload.startswith(b'%PDF');sha=hashlib.sha256(payload).hexdigest();expected='752d1eb10d466f704183cdde6f8813b51f0a8ed38d234f374b5485c9639518c3' if 'eia.gov' in url else issuer['pdf_sha256'];row={'url':url,'sha256':sha,'matches_prior_official_payload':sha==expected,'retrieved_at':now(),'headers':headers,'retrieval_clock_is_not_historical_first_public':True};dest=N/'artifacts/p1_pit_readiness_v34'/digest(row);commit_bundle(dest,{'document.pdf':payload,'retrieval.json':row},{'reserved_access':False});row['relative_bundle']=str(dest.relative_to(N));downloads.append(row)
        except Exception as error:downloads.append({'url':url,'state':'PUBLIC_RETRIEVAL_FAILED','error_type':type(error).__name__,'no_gate_promoted':True})
    eia=load(ORIGINAL/'reports/eia_2023_calibration_source_audit.json');assert file_hash(eia['CSV']['path'])==eia['CSV']['sha256'];assert file_hash(eia['PDF']['path'])==eia['PDF']['sha256'];eia_summary={'state':'BLOCKED_SOURCE_CONSISTENCY','checks':[x for x in eia['checks'] if x['format']=='csv'],'official_appendix_scope':'propane/propylene only; no authentic revised Table4 crude/gas/distillate payload','implied_prior_is_inference_not_observed':True,'tolerance_changed':False,'CSV_sha256':eia['CSV']['sha256']}
    freeze_present=bool(historical['freeze_receipt_present']);operational=bool(historical['operational_freeze_present']);assert not freeze_present and not operational
    future=future_probe(model_bound=(R/'reports/calibration_v34/calibration_frozen.json').exists(),clock_qualified=False,cohort_dates=0);save('future_readiness',future)
    report={'created_at':now(),'state':'BLOCKED_DATA_OR_FUTURE','sources':sources,'version_rows_audited':len(versions),'P1':{'qualified':False,'coverage':coverage,'daily_rows':len(daily),'missing_pay_dates':int(actions.pay_date.isna().sum()),'issuer_distribution_rows':24,'issuer_complete_coverage':False,'asof_cash_qualified':False,'per_session_gap_rows':len(gaps),'asset_year_gap_rows':len(yeargaps),'original_price_bundle_sha256':file_hash(market/'receipt.json'),'corporate_action_endpoint':'HTTP_403_ENTITLEMENT_NOT_RETRIED'},'documents':docs,'official_public_retrievals':downloads,'EIA2023':eia_summary,'future':future,'scientific_authorization_present_but_freeze_absent':True,'strict_final_claims_permitted':False,'reserved_evaluation_complete':False,'reserved_access':False,'GPU_training':0,'original_source_hash':code_hash(ORIGINAL),'v2_source_hash':code_hash(R)};save('readiness',report)
    text=['# V34 P1 / Tier-A / future readiness','',f"Executed per-version clock/hash audit: {len(versions)} source events, zero authenticated first-publication events. Each original immutable canonical bundle and payload hash validated; Tier B retained.",f"Raw open audit: {len(daily)} positive finite rows, 3386 sessions for each of 8 assets; prices exist. {len(actions)} action observations have {int(actions.pay_date.isna().sum())} missing payment dates; completeness/first-public clocks unqualified. 24 official IEF/TLT 2023 distributions are partial, not all-asset/year or first announcement evidence. Per-session and per-asset/year gap CSVs retain every audited row.",'','SEC [official FAQ](https://www.sec.gov/files/about/webmaster-faq.htm) distinguishes Accepted from first public availability; scheduled CFTC release is not dissemination proof. ALFRED [help](https://alfred.stlouisfed.org/help) defines database vintages, not authenticated original first-public clocks.','EIA [official Appendix E](https://www.eia.gov/petroleum/supply/weekly/archive/2023/2023_12_28/pdf/appendix_e.pdf) documents propane/propylene corrections, not authentic revised Table4 crude/gasoline/distillate levels. Arithmetic inferred prior cannot replace payload evidence; 2023 consistency remains BLOCKED. Live official PDF checksums/provenance are recorded, failed public retrievals retained.','Tiingo [dividend](https://www.tiingo.com/documentation/corporate-actions/dividends) and [split](https://www.tiingo.com/documentation/corporate-actions/splits) docs describe fields, not account entitlement or completeness. Prior 403 not retried; missing genuine SEC agent not invented. No credential inspection.','Permissible recovery: acquire authorized complete action/no-action session attestations, original announcements plus actual ex/payment/split events, original raw-open publication records and genuine as-of cash account data. For Tier-A require per-version raw payload linked to authenticated actual first dissemination plus correction history. No legal archive document by itself proves all versions.','No operational or scientific freeze is attested. No future cohort obtained, no forecasts issued, no earliest actual schedule can be stated. Two untouched future blocks of 52 mature weekly dates plus independent governance remain required after genuine freeze. The existing final authorization does not replace failed freeze/strict-PIT gates. No sealed final accessed, no PnL computed, no 2392 fits launched.'];(O/'V34_P1_TIER_A_FUTURE_READINESS.md').write_text('\n'.join(text)+'\n');print(json.dumps({'state':report['state'],'audited_versions':len(versions),'P1_daily_rows':len(daily),'actions':len(actions),'official_downloads':downloads,'future':future}),flush=True)
if __name__=='__main__':audit()